[0m22:14:55.157998 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107cb7370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ee6bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f150a0>]}


============================== 22:14:55.161088 | c8f496ec-fe9a-4e4b-98b4-b81087ea66cf ==============================
[0m22:14:55.161088 [info ] [MainThread]: Running with dbt=1.5.0
[0m22:14:55.161482 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/jordanstein/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m22:14:55.161885 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jordanstein/Dev/dbt-converter/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:14:55.162452 [debug] [MainThread]: Command `cli parse` failed at 22:14:55.162275 after 0.02 seconds
[0m22:14:55.162638 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107cb7370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ee6a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ee6970>]}
[0m22:14:55.162819 [debug] [MainThread]: Flushing usage events
[0m22:15:10.908125 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112dd0250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11433fb80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11436b310>]}


============================== 22:15:10.910097 | e8844f80-5673-4b30-8db3-d0be305c03e5 ==============================
[0m22:15:10.910097 [info ] [MainThread]: Running with dbt=1.5.0
[0m22:15:10.910444 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/jordanstein/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m22:15:10.910776 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jordanstein/Dev/dbt-converter/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:15:10.911360 [debug] [MainThread]: Command `cli parse` failed at 22:15:10.911278 after 0.01 seconds
[0m22:15:10.911571 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112dd0250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114381d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114381e80>]}
[0m22:15:10.911777 [debug] [MainThread]: Flushing usage events
[0m22:15:24.250466 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103d53370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104f82b80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104fb0070>]}


============================== 22:15:24.252944 | 1440a185-9694-477c-8a6c-1a41c8217b8e ==============================
[0m22:15:24.252944 [info ] [MainThread]: Running with dbt=1.5.0
[0m22:15:24.253285 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/jordanstein/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m22:15:24.253623 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jordanstein/Dev/dbt-converter/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:15:24.254134 [debug] [MainThread]: Command `cli parse` failed at 22:15:24.253963 after 0.01 seconds
[0m22:15:24.254326 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103d53370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104f82970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104f82940>]}
[0m22:15:24.254510 [debug] [MainThread]: Flushing usage events
[0m22:17:38.666119 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103247fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104478a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1044a51c0>]}


============================== 22:17:38.669337 | c527013b-75eb-4102-909c-d956f7854375 ==============================
[0m22:17:38.669337 [info ] [MainThread]: Running with dbt=1.5.0
[0m22:17:38.669711 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/jordanstein/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m22:17:38.670068 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jordanstein/Dev/dbt-converter/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:17:38.670498 [debug] [MainThread]: Command `cli parse` failed at 22:17:38.670422 after 0.02 seconds
[0m22:17:38.670686 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103247fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1044c2c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1044c2d60>]}
[0m22:17:38.670873 [debug] [MainThread]: Flushing usage events
[0m22:18:33.160167 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1071bbfd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1083eca30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1084191c0>]}


============================== 22:18:33.162719 | f6980eed-ac1f-4e80-8313-c1aa4c66835b ==============================
[0m22:18:33.162719 [info ] [MainThread]: Running with dbt=1.5.0
[0m22:18:33.163078 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/jordanstein/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m22:18:33.163415 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jordanstein/Dev/dbt-converter/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:18:33.163865 [debug] [MainThread]: Command `cli parse` failed at 22:18:33.163790 after 0.01 seconds
[0m22:18:33.164048 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1071bbfd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108437c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108437d60>]}
[0m22:18:33.164223 [debug] [MainThread]: Flushing usage events
[0m22:19:54.268702 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105976250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106babbb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106bd90a0>]}


============================== 22:19:54.271828 | c3c6067d-afee-48e6-b0b9-78a62510082f ==============================
[0m22:19:54.271828 [info ] [MainThread]: Running with dbt=1.5.0
[0m22:19:54.272209 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/jordanstein/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m22:19:54.272562 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jordanstein/Dev/dbt-converter/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:19:54.273195 [debug] [MainThread]: Command `cli parse` failed at 22:19:54.273123 after 0.02 seconds
[0m22:19:54.273513 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105976250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106bab9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106bab970>]}
[0m22:19:54.273720 [debug] [MainThread]: Flushing usage events
[0m17:21:19.914528 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1033ad1c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1045ec970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104622970>]}


============================== 17:21:19.923552 | 26765fd9-9781-430b-a1e9-21ecc3bf5bb8 ==============================
[0m17:21:19.923552 [info ] [MainThread]: Running with dbt=1.5.0
[0m17:21:19.923887 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/jordanstein/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m17:21:19.924207 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jordanstein/Dev/dbt-converter/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:21:19.924611 [debug] [MainThread]: Command `cli parse` failed at 17:21:19.924546 after 0.03 seconds
[0m17:21:19.924804 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1033ad1c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104645220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104645340>]}
[0m17:21:19.924974 [debug] [MainThread]: Flushing usage events
[0m17:21:40.085385 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107951220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bc5940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bc5130>]}


============================== 17:21:40.087976 | 72a9dcca-4957-48e4-b4a0-dca64be58992 ==============================
[0m17:21:40.087976 [info ] [MainThread]: Running with dbt=1.5.0
[0m17:21:40.088321 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/jordanstein/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m17:21:40.088649 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jordanstein/Dev/dbt-converter/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:21:40.089059 [debug] [MainThread]: Command `cli parse` failed at 17:21:40.088996 after 0.01 seconds
[0m17:21:40.089253 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107951220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bd1310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bd1e80>]}
[0m17:21:40.089437 [debug] [MainThread]: Flushing usage events
[0m17:21:47.973553 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1031dc0a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10441c340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104453760>]}


============================== 17:21:47.975417 | 1c8e21cf-a5ac-4498-8e13-44b94933ca54 ==============================
[0m17:21:47.975417 [info ] [MainThread]: Running with dbt=1.5.0
[0m17:21:47.975755 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/jordanstein/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m17:21:47.976085 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jordanstein/Dev/dbt-converter/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:21:47.976530 [debug] [MainThread]: Command `cli parse` failed at 17:21:47.976458 after 0.01 seconds
[0m17:21:47.976775 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1031dc0a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10441cbb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10441cb20>]}
[0m17:21:47.976947 [debug] [MainThread]: Flushing usage events
[0m17:22:02.335101 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107100700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108340940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108376700>]}


============================== 17:22:02.338148 | 70210d61-b421-4218-85bc-b4b60ddbf538 ==============================
[0m17:22:02.338148 [info ] [MainThread]: Running with dbt=1.5.0
[0m17:22:02.338498 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/jordanstein/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m17:22:02.338837 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jordanstein/Dev/dbt-converter/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:22:02.339243 [debug] [MainThread]: Command `cli parse` failed at 17:22:02.339177 after 0.01 seconds
[0m17:22:02.339505 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107100700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108340bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108340d00>]}
[0m17:22:02.339686 [debug] [MainThread]: Flushing usage events
